"""empty message

Revision ID: 4dc67e70f6ad
Revises: ae3bf2127a9c
Create Date: 2019-12-10 12:38:46.484164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc67e70f6ad'
down_revision = 'ae3bf2127a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('otp_valid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'otp_valid_until')
    # ### end Alembic commands ###
