"""empty message

Revision ID: ae3bf2127a9c
Revises: 
Create Date: 2019-12-10 12:34:02.253764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3bf2127a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=300), nullable=True),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('lname', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('start_location', sa.String(length=100), nullable=False),
    sa.Column('start_location_type', sa.String(length=20), nullable=False),
    sa.Column('end_location', sa.String(length=100), nullable=False),
    sa.Column('end_location_type', sa.String(length=20), nullable=False),
    sa.Column('run_time', sa.Time(), nullable=False),
    sa.Column('local_run_time', sa.Time(), nullable=False),
    sa.Column('local_timezone_offset', sa.Integer(), nullable=False),
    sa.Column('delay_tolerance', sa.Integer(), nullable=False),
    sa.Column('run_sunday', sa.Boolean(), nullable=False),
    sa.Column('run_monday', sa.Boolean(), nullable=False),
    sa.Column('run_tuesday', sa.Boolean(), nullable=False),
    sa.Column('run_wednesday', sa.Boolean(), nullable=False),
    sa.Column('run_thursday', sa.Boolean(), nullable=False),
    sa.Column('run_friday', sa.Boolean(), nullable=False),
    sa.Column('run_saturday', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phone'], ['accounts.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('accounts')
    # ### end Alembic commands ###
